# Generated by Django 2.1.5 on 2020-05-25 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('from_f', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 5, 25, 15, 4, 19, 377554), null=True)),
                ('idd', models.CharField(max_length=50)),
            ],
        ),
    ]
